# Generated by Django 5.2.7 on 2025-10-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='google_drive_folder_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='google_drive_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GoogleDriveSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_drive_file_id', models.CharField(max_length=255)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error'), ('conflict', 'Conflict')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_sync', to='core.document')),
            ],
        ),
    ]
